apiVersion: v1
kind: Template
metadata:
  name: selenium-template4demos
  description: Selenium template for Demos
  tags: ci
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      app: ${SERVICE_NAME}
    name: ${SERVICE_NAME}
  spec:
    tags:
    - from:
        kind: DockerImage
        name: docker.io/simontim/selenium-openshift:latest
      name: latest
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: ${SERVICE_NAME}
    name: ${SERVICE_NAME}
  spec:
    replicas: 1
    strategy:
      activeDeadlineSeconds: 21600
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    test: false
    selector:
      app: ${SERVICE_NAME}
      deploymentconfig: ${SERVICE_NAME}
    template:
      metadata:
        labels:
          app: ${SERVICE_NAME}
          deploymentconfig: ${SERVICE_NAME}
      spec:
        restartPolicy: Always
        terminationGracePeriodSeconds: 30
        dnsPolicy: ClusterFirst
        containers:
          - name: ${SERVICE_NAME}  
            image: " "
            ports:
              - containerPort: 4444
                protocol: TCP
              - containerPort: 5555
                protocol: TCP
            terminationMessagePath: /dev/termination-log
            imagePullPolicy: Always
        triggers:
        - type: ConfigChange
        - imageChangeParams:
            automatic: true
            containerNames:
            - ${SERVICE_NAME}
            from:
              kind: ImageStreamTag
              name: ${SERVICE_NAME}:latest
          type: ImageChange
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: ${SERVICE_NAME}
    name: ${SERVICE_NAME}
  spec:
    ports:
      - name: 4444-tcp
        protocol: TCP
        port: 4444
        targetPort: 4444
      - name: 5555-tcp
        protocol: TCP
        port: 5555
        targetPort: 5555
    type: ClusterIP
    selector:
      deploymentconfig: ${SERVICE_NAME}
- apiVersion: v1
  kind: Route
  metadata:
    labels: 
      app: ${SERVICE_NAME}
    name: ${SERVICE_NAME}
  spec:
    to:
      kind: Service
      name: ${SERVICE_NAME}
    port:
      targetPort: 4444-tcp
parameters:
- displayName: Selenium Service Name
  name: SERVICE_NAME
  required: false
  value: selenium

