apiVersion: v1
kind: Template
metadata:
  name: selenium-template4demos
  description: Selenium template for Demos
  tags: ci,selenium
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      app: ${SERVICE_NAME}
    name: selenium
  spec:
    tags:
    - from:
        kind: DockerImage
        name: docker.io/simontim/selenium-openshift:latest
      name: latest
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: ${SERVICE_NAME}
    name: ${SERVICE_NAME}
  spec:
    strategy:
      type: Rolling
      rollingParams:
        updatePeriodSeconds: 1
        intervalSeconds: 1
        timeoutSeconds: 600
        maxUnavailable: 25%
        maxSurge: 25%
      resources: {}
    triggers:
      - type: ConfigChange
      - type: ImageChange
        imageChangeParams:
          automatic: true
          containerNames:
            - selenium
          from:
            kind: ImageStreamTag
            name: 'selenium:latest'
    replicas: 1
    test: false
    selector:
      app: selenium
      deploymentconfig: selenium
    template:
      metadata:
        labels:
          app: selenium
      spec:
        containers:
          - name: selenium
            image: " "
            ports:
              - containerPort:4444
                protocol: TCP
              - containerPort: 5555
                protocol: TCP
            resources:
              limits:
                memory: 3Gi
              requests:
                memory: 2Gi
            terminationMessagePath: /dev/termination-log
            imagePullPolicy: Always
        restartPolicy: Always
        terminationGracePeriodSeconds: 30
        dnsPolicy: ClusterFirst
        securityContext: {}
- apiVersion: v1
  kind: Service
  metadata:
    name: selenium
  spec:
    ports:
      - name: 4444-tcp
        protocol: TCP
        port: 4444
        targetPort: 4444
      - name: 5555-tcp
        protocol: TCP
        port: 5555
        targetPort: 5555
    type: ClusterIP
    selector:
      app: selenium
- apiVersion: v1
  kind: Route
  metadata:
    name: selenium
  spec:
    to:
      kind: Service
      name: selenium
    port:
      targetPort: 4444-tcp

